---
apiVersion: apps/v1
kind: Deployment
metadata: 
 namespace: bggns
 name: bggapp-deploy
 labels:
  name: bggapp-deploy
spec:
 replicas: 3
 selector: 
  matchLabels:
   name: bggapp-po
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxSurge: 1
   maxUnavailable: 0
 template:
  metadata:
   name: bggapp-po
   labels:
    name: bggapp-po
  spec: 
   containers:
   - name: bggapp-container
     image: stackupiss/bgg-backend:v1
     imagePullPolicy: IfNotPresent
     livenessProbe:
      httpGet:
        path: /healthz
        port: 80
     envFrom:
     - configMapRef:
        name: bgg-cm
     - secretRef:
        name: bgg-secret
     ports: 
     - name: bggapp-port 
       containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
 namespace: bggns
 name: bggapp-svc
 labels:
  name: bggapp-svc
spec:
 type: ClusterIP
 selector: 
  name: bggapp-po
 ports:
 - port: 8080
   targetPort: bggapp-port  