---
apiVersion: apps/v1
kind: Deployment
metadata: 
 name: bggapp-deploy
 labels:
  name: bggapp-deploy
spec:
 replicas: 3
 selector: 
  matchLabels:
   name: bgg-app-po
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxSurge: 1
   maxUnavailable: 0
 template:
  metadata:
   name: bgg-app-po
   labels:
    name: bgg-app-po
  spec: 
   containers:
   - name: bgg-app-container
     image: stackupiss/bgg-backend:v2
     imagePullPolicy: IfNotPresent
     envFrom:
     - configMapRef:
        name: bgg-cm
     - secretRef:
        name: bgg-secret
     ports: 
     - name: bggapp-port 
       containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
 name: bggapp-svc
 labels:
  name: bggapp-svc
 namespace: bggns
spec:
 type: LoadBalancer
 selector: 
  name: bgg-app-po
 ports:
 - port: 80 
   targetPort: bggapp-port  