---
apiVersion: v1
kind: ConfigMap
metadata:
 namespace: bggns
 name: bgg-cm
 labels: 
  name: bgg-cm
data:
 BGG_DB_USER: root
 BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local

---
apiVersion: v1
kind: Secret
metadata: 
 namespace: bggns
 name: bgg-secret
data:
 BGG_DB_PASSWORD: Y2hhbmdlaXQ=
 