volumes:
  my-data:

networks:
  app-net:

services:
  mydb:
    image: stackupiss/northwind-db:v1 
    volumes:
       - my-data:/var/lib/mysql
    networks:
      - app-net

  myapp:
     image: stackupiss/northwind-app:v1
     environment:
       - APP_PORT=3000
       - DB_HOST=mydb
       - DB_USER=root
       - DB_PASSWORD=changeit
     ports:
       - 8080-9000:3000
     networks:
      - app-net

