---
apiVersion: apps/v1
kind: Deployment 
metadata:
 namespace: bggns
 name: bggapp-deploy
spec:
  template:
    spec:
      containers:
      - name: bggapp-container
        args:
        - --prefix 
        - /v1