---
apiVersion: apps/v1
kind: Deployment 
metadata:
 namespace: bggns
 name: bggapp-deploy
spec:
  template:
    spec:
      containers:
      - name: bggapp-container
        args:
        - --prefix 
        - /v1


#---
#apiVersion: autoscaling/v2beta2
#kind: HorizontalPodAutoscaler

#metadata:
# namespace: bggns
# name: bggapp-hpa
#spec:
# scaleTargetRef:
# - name: bggapp-deploy
#   args:
#   - --prefix
#   - /v1
  


