apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../Demo02

namePrefix: kuz-
nameSuffix: -stg

commonLabels:
  deployDate: 31-mar-22

replicas:
- name: dov-deploy
  count: 1
