---
apiVersion: v1
kind: ConfigMap
metadata:
 name: dov-cm
 labels: 
  name: dov-cm
data:
 INSTANCE_NAME: dov-cm-bear-test
 
---
apiVersion: apps/v1
kind: Deployment
metadata: 
 name: dov-deploy
 labels:
  name: dov-deploy
spec:
 replicas: 3
 selector: 
  matchLabels:
   name: dov-pod
 template:
  metadata:
   name: dov-pod
   labels:
    name: dov-pod
    dept: engg 
# namespace: myNS -- if not defined now, have to define later.
  spec: 
   containers:
   - name: dov-container
     image: stackupiss/dov-bear:v2
     imagePullPolicy: IfNotPresent
     env:
     - name: INSTANCE_NAME
       valueFrom:
        fieldRef:
         fieldPath: status.podIP
     envFrom:
      - configMapRef:
         name: dov-cm
     ports: 
     - containerPort: 3000
 
