---
apiVersion: v1
kind: Secret
metadata:
 namespace: wpns 
 name: wpdb-secret
 labels:
  name: wpdb-secret
type: Opaque
data:
 ROOT_PASSWORD: cm9vdHBhc3M=
 WORDPRESS_DB_PASSWORD: cm9vdHBhc3M=

#kubectl api-resource | grep mysql to get the apiversion and kind
--- 
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
 namespace: wpns
 name: wpdb-cluster
 labels:
  name: wpdb-cluster
spec:
 replicas: 3
 secretName: wpdb-secret
 mysqlVersion: "8.0" 
 # to get version number from mysql images in docker hub
 volumeSpec:
  persistentVolumeClaim:
    accessModes:
    - ReadWriteOnce
    resources:
     requests:
      storage: 1Gi
    storageClassName: do-block-storage 
#k get sc to get the storage class name